"""Mint a development JWT for testing the gateway.

Reads the private key generated by dev_jwks_server.py and prints a signed JWT.

Usage:
    python scripts/dev_token.py                  # regular user token
    python scripts/dev_token.py --admin          # token with admin role
    python scripts/dev_token.py --sub myuser     # custom subject

Copy the printed token and use it as:
    curl -H "Authorization: Bearer <token>" http://localhost:8000/...
"""

import argparse
import os
import sys
import time

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))

from jose import jwt

KEYS_DIR = os.path.join(os.path.dirname(__file__), "..", ".dev-keys")
PRIVATE_KEY_PATH = os.path.join(KEYS_DIR, "private.pem")
KID = "dev-key-1"


def mint_token(sub: str, roles: list[str], ttl: int = 3600) -> str:
    if not os.path.exists(PRIVATE_KEY_PATH):
        sys.exit(
            "No private key found. Run scripts/dev_jwks_server.py first to generate keys."
        )
    with open(PRIVATE_KEY_PATH) as f:
        private_pem = f.read()

    now = int(time.time())
    claims = {
        "sub": sub,
        "email": f"{sub}@dev.local",
        "roles": roles,
        "iat": now,
        "exp": now + ttl,
    }
    return jwt.encode(claims, private_pem, algorithm="RS256", headers={"kid": KID})


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Mint a dev JWT for the gateway.")
    parser.add_argument("--sub", default="dev-user", help="JWT subject (user ID)")
    parser.add_argument("--admin", action="store_true", help="Include admin role")
    parser.add_argument("--ttl", type=int, default=3600, help="Token TTL in seconds")
    args = parser.parse_args()

    roles = ["admin"] if args.admin else []
    token = mint_token(sub=args.sub, roles=roles, ttl=args.ttl)

    print(token)
